version: "2"

services:
  app:
    build: ./
    links:
      - mongo

    environment:
      - MONGODB_URI=mongodb://mongo_1:27017/gambit-
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
